[package]
name = "coordgen"
version = "0.1.0"
edition = "2018"

[build-dependencies]
cc = "1.0.70"
cmake = "0.1.45"

[dev-dependencies]
reqwest = { version = "0.11.4", features = ["rustls-tls", "blocking", "json"], default-features = false}
serde = { version = "1.0", features = ["derive"] }
